
package com.ws.clientByServlet;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloJAXWSImplService", targetNamespace = "http://server.ws.com/", wsdlLocation = "http://localhost:8080/service/helloJAXWS?wsdl")
public class HelloJAXWSImplService
    extends Service
{

    private final static URL HELLOJAXWSIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/service/helloJAXWS?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HELLOJAXWSIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloJAXWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloJAXWSImplService() {
        super(HELLOJAXWSIMPLSERVICE_WSDL_LOCATION, new QName("http://server.ws.com/", "HelloJAXWSImplService"));
    }

    /**
     * 
     * @return
     *     returns HelloJAXWS
     */
    @WebEndpoint(name = "HelloJAXWSImplPort")
    public HelloJAXWS getHelloJAXWSImplPort() {
        return (HelloJAXWS)super.getPort(new QName("http://server.ws.com/", "HelloJAXWSImplPort"), HelloJAXWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloJAXWS
     */
    @WebEndpoint(name = "HelloJAXWSImplPort")
    public HelloJAXWS getHelloJAXWSImplPort(WebServiceFeature... features) {
        return (HelloJAXWS)super.getPort(new QName("http://server.ws.com/", "HelloJAXWSImplPort"), HelloJAXWS.class, features);
    }

}
