
package com.springmvc.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloJAXWSImplService", targetNamespace = "http://server.ws.springmvc.com/", wsdlLocation = "http://localhost:8080/service/springHelloJAXWS?wsdl")
public class HelloJAXWSImplService
    extends Service
{

    private final static URL HELLOJAXWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOJAXWSIMPLSERVICE_EXCEPTION;
    private final static QName HELLOJAXWSIMPLSERVICE_QNAME = new QName("http://server.ws.springmvc.com/", "HelloJAXWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service/springHelloJAXWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOJAXWSIMPLSERVICE_WSDL_LOCATION = url;
        HELLOJAXWSIMPLSERVICE_EXCEPTION = e;
    }

    public HelloJAXWSImplService() {
        super(__getWsdlLocation(), HELLOJAXWSIMPLSERVICE_QNAME);
    }

    public HelloJAXWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOJAXWSIMPLSERVICE_QNAME, features);
    }

    public HelloJAXWSImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOJAXWSIMPLSERVICE_QNAME);
    }

    public HelloJAXWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOJAXWSIMPLSERVICE_QNAME, features);
    }

    public HelloJAXWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloJAXWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloJAXWS
     */
    @WebEndpoint(name = "HelloJAXWSImplPort")
    public HelloJAXWS getHelloJAXWSImplPort() {
        return super.getPort(new QName("http://server.ws.springmvc.com/", "HelloJAXWSImplPort"), HelloJAXWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloJAXWS
     */
    @WebEndpoint(name = "HelloJAXWSImplPort")
    public HelloJAXWS getHelloJAXWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.springmvc.com/", "HelloJAXWSImplPort"), HelloJAXWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOJAXWSIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOJAXWSIMPLSERVICE_EXCEPTION;
        }
        return HELLOJAXWSIMPLSERVICE_WSDL_LOCATION;
    }

}
