
package com.springmvc.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "springHelloJaxWs", targetNamespace = "http://server.ws.springmvc.com/", wsdlLocation = "http://localhost:8080/service/springHelloJAXWS?wsdl")
public class SpringHelloJaxWs
    extends Service
{

    private final static URL SPRINGHELLOJAXWS_WSDL_LOCATION;
    private final static WebServiceException SPRINGHELLOJAXWS_EXCEPTION;
    private final static QName SPRINGHELLOJAXWS_QNAME = new QName("http://server.ws.springmvc.com/", "springHelloJaxWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service/springHelloJAXWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPRINGHELLOJAXWS_WSDL_LOCATION = url;
        SPRINGHELLOJAXWS_EXCEPTION = e;
    }

    public SpringHelloJaxWs() {
        super(__getWsdlLocation(), SPRINGHELLOJAXWS_QNAME);
    }

    public SpringHelloJaxWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPRINGHELLOJAXWS_QNAME, features);
    }

    public SpringHelloJaxWs(URL wsdlLocation) {
        super(wsdlLocation, SPRINGHELLOJAXWS_QNAME);
    }

    public SpringHelloJaxWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPRINGHELLOJAXWS_QNAME, features);
    }

    public SpringHelloJaxWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpringHelloJaxWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloJAXWS
     */
    @WebEndpoint(name = "helloJaxWsPort")
    public HelloJAXWS getHelloJaxWsPort() {
        return super.getPort(new QName("http://server.ws.springmvc.com/", "helloJaxWsPort"), HelloJAXWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloJAXWS
     */
    @WebEndpoint(name = "helloJaxWsPort")
    public HelloJAXWS getHelloJaxWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.springmvc.com/", "helloJaxWsPort"), HelloJAXWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPRINGHELLOJAXWS_EXCEPTION!= null) {
            throw SPRINGHELLOJAXWS_EXCEPTION;
        }
        return SPRINGHELLOJAXWS_WSDL_LOCATION;
    }

}
